services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped 
    volumes:
      - ollama:/root/.ollama      
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: chatbot_app
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "8501:8501"
    restart: unless-stopped
    command: chatbot_app run app.py --server.address=0.0.0.0 --server.port=8501

volumes:
  ollama: